import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/common/elements/navbar";
import { Footer } from "@/common/elements/footer";
import { Cta } from "@/common/elements/cta";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";
export const fetchCache = "force-no-store";

const fetchData = async () => {
  let data = {
    properties: [],
    areas: [],
  };
  try {
  } catch (error) {
    console.log("error", error);
  }
  return data;
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await fetchData();

  return (
    <html lang="en">
      <body>
        
        <Navbar properties={data.properties} areas={data.areas} />
        {children}
        <Footer properties={data.properties} />
        {/* <Cta /> */}
      </body>
    </html>
  );
}
